FROM ubuntu:latest
RUN apt-get update && apt-get install -y curl wget php-cli php-mbstring php-xml php-curl unzip
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
