name: PHPUnit

on:
  workflow_dispatch:

env:
  APP_NAME: filefinder

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: ['8.3']
        server-versions: ['stable32']

    name: php${{ matrix.php-versions }}-${{ matrix.server-versions }}

    services:
      mysql:
        image: mariadb:10.11
        environment:
          MYSQL_ROOT_PASSWORD: 'nextcloud'
          MYSQL_PASSWORD: 'nextcloud'
          MYSQL_USER: 'nextcloud'
          MYSQL_DATABASE: 'nextcloud'

      elasticsearch:
        image: elasticsearch:9.4.2
        environment:
          - ELASTIC_PASSWORD=elastic
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - xpack.security.enabled=false

    steps:
      - name: Checkout server
        uses: actions/checkout@v6
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}
          submodules: true

      - name: Checkout app
        uses: actions/checkout@v6
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, gd, zip

      - name: Set up PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=mysql --database-name=nextcloud --database-host=mysql --database-port=3306 --database-user=nextcloud --database-pass=nextcloud --admin-user=admin --admin-pass=admin
          ./occ app:enable --force ${{ env.APP_NAME }}

      - name: PHPUnit
        working-directory: apps/${{ env.APP_NAME }}
        run: ./vendor/bin/phpunit -c tests/phpunit.xml --testsuite integration